### ISSUE TITLE
docs building error with sphinx 1.3.1

### ISSUE THREAD

**Issue by migueldvb** [spacetelescope/pyasdf#134]
Building the HTML documentation with sphinx 1.3.1 and the latest astropy-helpers fails with the following error:

```
# Sphinx version: 1.3.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   11 added, 0 changed, 0 removed
#   reading sources... [  9%] api/pyasdf.AsdfExtension
#   reading sources... [ 18%] api/pyasdf.AsdfFile
#   reading sources... [ 27%] api/pyasdf.AsdfType
#   reading sources... [ 36%] api/pyasdf.Stream
#   reading sources... [ 45%] api/pyasdf.ValidationError
#   reading sources... [ 54%] api/pyasdf.fits_embed.AsdfInFits
#   reading sources... [ 63%] api/pyasdf.open
#   reading sources... [ 72%] api/pyasdf.test
#   reading sources... [ 81%] index
# Loaded extensions:
#   sphinx.ext.autosummary (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.pngmath (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/pngmath.py
#   astropy_helpers.sphinx.ext.changelog_links (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/changelog_links.py
#   sphinx.ext.autodoc (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.coverage (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.inheritance_diagram (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/inheritance_diagram.py
#   astropy_helpers.sphinx.ext.doctest (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/doctest.py
#   astropy_helpers.sphinx.ext.autodoc_enhancements (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/autodoc_enhancements.py
#   example (unknown version) from sphinxext/example.py
#   astropy_helpers.sphinx.ext.viewcode (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/viewcode.py
#   astropy_helpers.sphinx.ext.automodsumm (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/automodsumm.py
#   astropy_helpers.sphinx.ext.numpydoc (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/numpydoc.py
#   astropy_helpers.sphinx.ext.astropyautosummary (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/astropyautosummary.py
#   sphinx.ext.graphviz (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/graphviz.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /usr/lib/python3.4/site-packages/matplotlib/sphinxext/plot_directive.py
#   astropy_helpers.sphinx.ext.smart_resolver (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/smart_resolver.py
#   astropy_helpers.sphinx.ext.tocdepthfix (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/tocdepthfix.py
#   astropy_helpers.sphinx.ext.automodapi (unknown version) from /home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.1.dev427-py3.4.egg/astropy_helpers/sphinx/ext/automodapi.py
#   sphinx.ext.todo (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/todo.py
#   alabaster (0.7.4) from /usr/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.intersphinx (1.3.1) from /usr/lib/python3.4/site-packages/sphinx/ext/intersphinx.py
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python3.4/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.4/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.4/site-packages/sphinx/transforms.py", line 129, in apply
    if has_child(node.parent, nodes.caption):
  File "/usr/lib/python3.4/site-packages/sphinx/transforms.py", line 116, in has_child
    return any(isinstance(child, cls) for child in node)
TypeError: 'NoneType' object is not iterable
```

**Comment by mdboom** [comment]
Thanks.  I noticed this the other day, but haven't put in the time to update it for Sphinx 1.3
